### ISSUE TITLE
After Updating to 3.0, TWLoader Crashes

### ISSUE THREAD

**Issue by rpalmon** [Robz8/TWLoader#89] opened 2017-01-22 06:21 UTC
So I updated TWLoader to 3.0 but now when it finishes downloading box art and updates bootstrap (unofficial) it crashes.

**Comment by rpalmon** [comment] 2017-01-22 06:22
Then restarting the system

**Comment by Robz8** [comment] 2017-01-22 06:24
Did you specify your rom paths?

**Comment by rpalmon** [comment] 2017-01-22 06:28
I'll check that tomorrow as I dont have my computer on me.

**Comment by Bryguy5849** [comment] 2017-01-22 06:33
Mine crashes when going through my games and only crashes when it gets to a specific game. Any idea what's causing this?

**Comment by Robz8** [comment] 2017-01-22 06:38
Try clearing the following folders:
"sdmc:/_nds/twloader/boxart/"
"sdmc:/_nds/twloader/bnricons/"
"sdmc:/_nds/twloader/boxart/flashcard/"
"sdmc:/_nds/twloader/bnricons/flashcard"

**Comment by Bryguy5849** [comment] 2017-01-22 06:48
That didn't work

**Comment by Robz8** [comment] 2017-01-22 06:49
Sorry. I can't fix it if I'm not getting the crash.

**Comment by Bryguy5849** [comment] 2017-01-22 06:49
More specifically I'm in the menu, and it crashes when when I'm going through my nds files

**Comment by Bryguy5849** [comment] 2017-01-22 06:50
This only started happened after updating? It's your app, you can't just not fix it if it's not working properly. Well you could but that'd be sad haha

**Comment by DarthVitrial** [comment] 2017-01-22 06:54
I'm having this issue too when it reaches a specific game, only in this version. Is there a way to create a crash dump for diagnostics?

**Comment by Robz8** [comment] 2017-01-22 06:57
In Luma settings, set Dev features to ErrDisp.

**Comment by Robz8** [comment] 2017-01-22 07:00
Are you three using O3DS'?

**Comment by Bryguy5849** [comment] 2017-01-22 07:02
I'm doing a %100 fresh install. I'll update you in a second my friend!

**Comment by Bryguy5849** [comment] 2017-01-22 07:03
Now I'm just straight crashing at the logo. I'm on o3DS LumaAl9h

**Comment by DarthVitrial** [comment] 2017-01-22 07:10
Nope, n3DS.
Here's the crash dump from Luma:
https://mega.nz/#!0gsBmI5Q!Tu48seEmk5kyX8SX66vq27iixjNxq-VARvvlW6BSaac

**Comment by Margen67** [comment] 2017-01-22 19:07
Duplicate of #91

**Comment by hectortillo** [comment] 2017-01-23 02:05
Rpalmon do you have tried the last update?

**Comment by DarthVitrial** [comment] 2017-01-23 03:34
It's fixed for me in the newest update.

**Closed** 2017-01-23 03:42 UTC
