### ISSUE TITLE
Crashes after first startup

### ISSUE THREAD

**Issue by ChromoTec** [Robz8/TWLoader#503] opened 2018-06-04 17:34 UTC
### Your 3DS

Tell us which console do you have:

- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

After opening the TWLoader application, it should boot into a screen showing all installed ROMs, allowing me to select the one I want to use.
### Actual behaviour

After the "enhanced with pseudo-HDR" screen, it gives me a crash dump error.

### Steps to reproduce

1. Open TWLoader for the first time
2. Exit the application
3. Re-open the application

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
[crash_dump_00000000.zip](https://github.com/Robz8/TWLoader/files/2069329/crash_dump_00000000.zip)
```
### Extra information

This happens after the first time opening when the GAMESETTINGS_PATH value in the TWLoader settings.ini file is set to a nonexistent location (in my case, `sd:/_nds/twloader/gamesettings/0025 - Super Mario 64 DS (Japan).nds` ) Deleting the GAMESETTINGS_PATH line in the settings.ini fixes the problem for the next startup, but after that startup the same problem occurs.

**Comment by Robz8** [comment] 2018-06-04 17:45
Try editing per-game settings for that game. Set the clock speed to NTR, press B, then exit TWLoader.

**Comment by ChromoTec** [comment] 2018-06-04 18:39
I still get the same error, the only difference is that now for a split second it boots into my roms, and then it gives me the "an exception occurred" screen again.

**Comment by Robz8** [comment] 2018-06-06 18:40
A part of the issue is pretty much solved, so closing this.

**Closed by Robz8** 2018-06-06 18:40 UTC
