### ISSUE TITLE
nintendo 2ds plays all the 3ds games

### ISSUE THREAD

**Issue by yrgentmessage** [Robz8/TWLoader#470] opened 2018-04-18 23:46 UTC
i did what was told and loader not working i need help so and alot of the video dont work can please respond i did what was told and put mario kart ds in folder  created it and the twaloader not poping up in my menu on micro sd card so yeah unless its the loader it should have poped up fbi our cia to run but dident my sd card good so yeah i have 32 gig please respond

**Comment by Robz8** [comment] 2018-04-18 23:57
Where are you putting the Mario Kart DS ROM?

**Comment by yrgentmessage** [comment] 2018-04-19 00:00
in the rom folder and the twaloader isnt showing up i know you dont need flashcart for the loader it should poped up cia our fbi loader installer our twa but its not its 2ds that plays all teh 3ds games

**Comment by Robz8** [comment] 2018-04-19 00:08
Are you putting the ROM in `sd:/roms/nds/`?
If so, delete `settings.ini` at `sd:/_nds/twloader`.
Also, make sure the ROM has .nds at the end, and is not in a .zip file.

**Comment by yrgentmessage** [comment] 2018-04-19 00:42
i did that still not loading up i put in nintendo 3ds folder just nds and 3ds stuff and made rom folder and still not popping up i bought micro sd card reader and regular one came with it so yeah im stuck in videos it shows it works i will try and older one since i dont use online play but i dont know if it will so yeah i did what the enstruction said

**Comment by Robz8** [comment] 2018-04-19 00:57
Are you able to record a video of what's happening?

**Comment by yrgentmessage** [comment] 2018-04-19 21:06
not right now whats happing is the loader not showing up i will try older one and see but im woundering if u guys are having the same problem

**Comment by Robz8** [comment] 2018-04-19 21:10
So it's not showing up in the HOME Menu.
Also, don't try an old version. Is there an error when trying to install the CIA?

**Comment by yrgentmessage** [comment] 2018-04-21 15:58
no when i try installing it wont show in menu i read the instruction right and still not loading our showing i dont wanna have to bye a flashcart if i dont need to so i really need help on this my friend brandon had modifed 3ds with flashcart with roms but he been to busy on helping me so yeah if u guys need rom site check loveroms.com ok guys have fun with it please reply i been busy so it toke me while to reply they told me not to watch the videos so yeah im stuck and clueless why its not showing up on sd micro card i bought the reader for it its a 32 gig sd card so plenty of room i know its need to be there compat list so yeah

**Comment by Robz8** [comment] 2018-04-21 17:31
Try the .3dsx of TWLoader instead, then.
First, download boot.3dsx [here](https://github.com/fincs/new-hbmenu/releases), then place it on the SD root.
Then on your 2DS, launch Download Play, then hold L+DOWN+SELECT, then go to `Miscellaneous options`, then `Switch the hb. title to the current app.`, and finally re-launch Download Play, and you'll be in he Homebrew Launcher to launch TWLoader.

**Comment by Robz8** [comment] 2018-04-25 19:26
It's not LEFT+DOWN+SELECT. It's L+DOWN+SELECT. L, as in the actual "L" button.

**Comment by Robz8** [comment] 2018-04-25 20:44
DOWN is the D-pad down.

**Comment by yrgentmessage** [comment] 2018-04-25 20:50
can show me video on how to do this right way i mean with twa loader and all so that way i know how to do it least i got genral idea on how to thank you for your help yea i pressed the l buttion then down on d pad and then select it wouldent open under play at all

**Comment by yrgentmessage** [comment] 2018-04-25 20:50
with a video our something

**Comment by Robz8** [comment] 2018-04-25 20:58
Many would disagree on a video guide, as they get outdated.

Did you hold the buttons down at the same time?

**Comment by yrgentmessage** [comment] 2018-04-30 14:51
its the 2ds xl that plays em all i found my box so i need the right instruction for the 2ds so yeah please help thanks

**Comment by Robz8** [comment] 2018-04-30 14:59
Please answer my question.

**Comment by Robz8** [comment] 2018-04-30 15:34
Do you have Luma at all?

**Comment by yrgentmessage** [comment] 2018-04-30 15:47
im using the newiest one that on my sd card i think as cfw if i remeber right i had to make a folder called luma and put in it so yeah what ever the newiest verison is so yeah

**Comment by yrgentmessage** [comment] 2018-04-30 16:45
the question i have i need one for 2ds xl version anyways

**Comment by Robz8** [comment] 2018-04-30 18:07
Is your L button working at all?

**Comment by yrgentmessage** [comment] 2018-04-30 21:57
yeah it lets me activate the cam and everything so yeah the l buttion works

**Comment by yrgentmessage** [comment] 2018-05-01 16:14
can u get someone else to help me out this today i would really like to get my gameboy up and going today so i can enjoy because i dont want my nephew hogging it bad enough he hogs my xbox one s so yeah

**Comment by Robz8** [comment] 2018-05-01 16:29
Where are you holding the L+DOWN+SELECT button combo?

**Comment by yrgentmessage** [comment] 2018-05-01 16:41
yes i am and it doesent work  the l buttion works so does the select buttion and down buttion but holding down all at once wont bring the menu up so yeah im stuck confused and kinda werry about why it wont let me i should have had finshed along time ago like i did with my wii  almsot 4 years ago when home brew orginally came out so yeah please help i need the 2ds xl instruction so yeah

**Comment by Robz8** [comment] 2018-05-01 17:06
I asked *where* are you holding it, not *are you*.

**Comment by Robz8** [comment] 2018-05-01 18:25
Do you not know the difference between "where" and "are"? They aren't the same.
By "where", I mean, are you holding it before powering on the system, or are you holding it at the 3DS HOME Menu?

**Comment by Robz8** [comment] 2018-05-01 18:31
If you're holding the combo at the 3DS HOME Menu, where you should be holding the combo, then you'll have to try an out of date solution.
Use [Hourglass9](https://github.com/d0k3/Hourglass9/releases) to dump H&S .app, and use [this](https://github.com/d0k3/Universal-Inject-Generator).

**Comment by Jolty95** [comment] 2018-05-01 18:32
After reading several times, I still don't know what the problem is ._. (Just sayin')

**Comment by Robz8** [comment] 2018-05-01 18:35
@Jolty95 The problem is, he can't access homebrew (TWLoader, in this case) in any way, since he doesn't have FBI installed, and he can't access Rosalina menu, despite him holding the correct button combo.

**Comment by Jolty95** [comment] 2018-05-01 18:38
@Robz8 So basically, he don't have CFW and neither homebrew
Just following 3ds.guide isn't the answer?

**Comment by Jolty95** [comment] 2018-05-01 18:45
@Robz8 I think that maybe he just downloaded Luma and put on SD without really... "installing" it

**Comment by yrgentmessage** [comment] 2018-05-01 18:45
i have it on my sd card and where you go into the play section holding l buttion down and then select it doesent work i will try it at home screen the fbi doesent appear in screen like it does for other people and stuff so yeah nope it doesent work on menu screen at home i have those in folder on sd card like it said to do but nothing is still happing its the 2ds xl modle so i guess i will try hour glass to see what happing

**Comment by yrgentmessage** [comment] 2018-05-01 18:52
there no way for me to put a print scheme picture on hear to show you guys its on the sd card its self so i have no way to verify you guys to show its there and done i will try hourglass

**Comment by Robz8** [comment] 2018-05-01 19:31
Does the Luma settings screen appear, when holding SELECT when turning on your 2DS?
Note that I'm not referring to the Rosalina menu this time.

**Comment by yrgentmessage** [comment] 2018-05-01 19:50
no it does not i tryed that so yeah

**Comment by yrgentmessage** [comment] 2018-05-01 19:50
should i reformat my gameboy and trying it again our do that one

**Comment by Robz8** [comment] 2018-05-01 20:00
Since you have no way of showing the SD card files from a picture, I'll ask this:
Do you have Luma's `boot.firm` on the SD card root?

**Comment by yrgentmessage** [comment] 2018-05-01 20:03
no i dont were can get al the stuff im gonna need for this rtto work at maybe i just wipe my sd card format nd then start over on it can send me a link for everything including god mod firm and install instruction for luma and everything else and i will try it again

**Comment by Robz8** [comment] 2018-05-01 20:14
https://3ds.hacks.guide/

**Comment by yrgentmessage** [comment] 2018-05-01 20:26
helpppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp ?

**Comment by yrgentmessage** [comment] 2018-05-01 20:27
help with this i dident mean to scream help like that i wanted help with this to do it right thanks

**Comment by yrgentmessage** [comment] 2018-05-01 20:29
help with this please help with this i need help on this to get right thanks

**Comment by Robz8** [comment] 2018-05-01 20:43
Just to make sure, you have boot9strap installed, right?

**Comment by yrgentmessage** [comment] 2018-05-01 20:49
i dont have of it installe dits all on my sd card it wount let me get to roslina menu when i hold it down it wount let me get to miss menu our anything else like that so yeah

**Comment by yrgentmessage** [comment] 2018-05-01 20:50
i have it all on my sd card in folders likek it said to do

**Comment by yrgentmessage** [comment] 2018-05-01 20:50
fbi wont pop up our cia wont either so ueah

**Comment by Robz8** [comment] 2018-05-01 20:53
Please follow this guide: https://3ds.hacks.guide/ It's the best guide there is.
As soon as you follow it, you'll be able to install TWLoader.

**Comment by yrgentmessage** [comment] 2018-05-01 20:54
iw ill try it on my orginal sd card it came with i nvr thought about doing that because i have 32 gig sd card now but the orginal only 4 gig and wont hold very many games on it either

**Comment by Jolty95** [comment] 2018-05-01 21:39
So I was right and you only have the files lying around on your sd
Closing this since this "issue" is not related with TWLoader.
For @yrgentmessage just follow the guide Robz told you several times in order to install a CFW. You can select whichever language you speak

**Closed by Jolty95** 2018-05-01 21:39 UTC
