### ISSUE TITLE
Application freezes on boot logo as of v3.2

### ISSUE THREAD

**Issue by bui** [Robz8/TWLoader#169] opened 2017-02-07 04:27 UTC
Using TWLoader 3.3, Luma on emunand, system version 11.2
Even after a fresh install (deleted _nds dir and copied from release, installed TWLNAND CIA on both sys and emunand), the system completely freezes at the stage where it's just the logo with the red outline on the top screen. 

Any ideas?

**Comment by Robz8** [comment] 2017-02-07 04:30
Nope.

**Comment by bui** [comment] 2017-02-07 05:24
I did some testing, and 3.0 seems to be the breaking version. 2.4.2 works perfectly fine.

**Comment by bui** [comment] 2017-02-07 05:43
OK, disregard that, 3.2 is the version that breaks. I should probably mention I am using a JPN system, and I do not have a card in slot-1, if that can help narrow down the problem.

**Comment by Margen67** [comment] 2017-02-07 07:56
Why are you using emuNAND?

**Comment by elliot-forty-two** [comment] 2017-02-07 10:09
I am also having this problem, I copied and overwrote with the files from 3.3 and getting stuck at the splash screen. Is there any debug I can get out of it to help?

**Comment by elliot-forty-two** [comment] 2017-02-07 10:40
I can confirm that it's 3.2 that breaks for me, 3.1 loads OK. I'm using an o3DSXL with 11.2.0 EUR, A9LH and Luma3DS. TWLoader is installed from CIA.

**Comment by Margen67** [comment] 2017-02-07 10:45
If you're using a non-A9LH entrypoint you should use http://3ds.guide/
If you already have A9LH then https://3ds.guide/move-emunand

**Comment by elliot-forty-two** [comment] 2017-02-07 10:48
I'm using A9LH with Luma on SysNAND so the freeze doesn't appear to be EmuNAND related.

**Comment by elliot-forty-two** [comment] 2017-02-07 11:21
It's getting stuck just after the Wifi status is established as enabled. If I turn Wifi off then it loads fine both with 3.2 and 3.3.

**Comment by elliot-forty-two** [comment] 2017-02-07 12:05
I found how to enable the log file. It's getting stuck after:
`Method: <Main.LoadBootstrapConfig> : Message:<Bootstrap configuration loaded successfully>`
with 2 or 4 of:
`Method: <WifiStatus> : Message: <Active internet connection found> 	Additional info:<11:22>`
and should get to this according to a run with Wifi off:
`Method: <LoadColor()> : Message:<Colors load successfully>`

It must be getting stuck in checkBootstrapVersion(), probably in the loop within downloadFile() as it would have called checkWifiStatus() twice by then. I'm also getting no version file written to the SD so perhaps it's stuck waiting on a socket or is in a redirect loop with a 3xx HTTP status?

**Comment by Clement95** [comment] 2017-02-07 21:36
The problem surely appears every time TWLoader is being updated (precisely when there is the step to update TWL Nand Size (Sorry for English)

**Comment by Jolty95** [comment] 2017-02-08 12:09
Duplicated and solved https://github.com/Robz8/TWLoader/pull/174

**Comment by bui** [comment] 2017-02-09 01:24
This specific issue still persists for me on 3.3.1. @elliot-forty-two, are you able to replicate?

**Comment by Robz8** [comment] 2017-02-09 01:37
For some reason, creating "log" in "sdmc:/_nds/twloader/" fixes the issue.

**Comment by bui** [comment] 2017-02-09 01:48
@Robz8 Nope, still looping over `WifiStatus`.

````************** Log file created at  1:44 **************
Method: <Main.Font loading> :
		Message:<Fonts load correctly>
Method: <Main.Verfile (ROMFS)> :
		Message: <Successful reading ver from ROMFS> 	Additional info:<Ver. 3.3.1   >
Method: <Settings.LoadSettings> :
		Message:<Settings loaded successfully>
Method: <Main.LoadBootstrapConfig> :
		Message:<Bootstrap configuration loaded successfully>
Method: <WifiStatus> :
		Message: <Active internet connection found> 	Additional info:< 1:44>
Method: <WifiStatus> :
		Message: <Active internet connection found> 	Additional info:< 1:44>
Method: <WifiStatus> :
		Message: <Active internet connection found> 	Additional info:< 1:45>
Method: <WifiStatus> :
		Message: <Active internet connection found> 	Additional info:< 1:45>
````

**Comment by Robz8** [comment] 2017-02-09 03:13
Any ideas @bakawun and @Jolty95?

**Comment by Jolty95** [comment] 2017-02-09 08:51
I'll take a look bug I needed he/she to help me testing ;)

**Comment by bakawun** [comment] 2017-02-09 08:56
We can and should expand the logging to include everything.
So if and when i have time i will make the log extremely verbose.
This will not slow down the app because logging is now disabled by default.

Another thing to note is that it may be the case that this just does not work from emunand at all.

**Comment by Jolty95** [comment] 2017-02-09 08:57
No.
I think was it's causing the problem and I'm working on it. Gimme some time to fix it

**Comment by bakawun** [comment] 2017-02-09 09:01
Great!

I will still add more logging though as i go through the code.

**Comment by Jolty95** [comment] 2017-02-09 09:04
I've added some too. Wait until I finish to avoid conflicts in the PR :)

**Comment by Jolty95** [comment] 2017-02-09 09:12
I found a big bug and now It's solved. I'll continue looking at the code just to be sure that was the problem.

**Comment by Jolty95** [comment] 2017-02-09 09:16
@bui Can you show in a pic the content of `SD:\_nds\twloader` ?

**Comment by bui** [comment] 2017-02-09 09:41
![image](https://cloud.githubusercontent.com/assets/1788767/22777688/f27b300c-eeab-11e6-940c-6e1c7bf886ee.png)

**Comment by elliot-forty-two** [comment] 2017-02-09 09:47
Still a problem for me with 3.3.1 on SysNAND. I tried to compile TWLoader myself to do some more testing/debugging but my compiled CIA just crashes during the splash screen.

I did a packet capture with 3.3 and there are many repeated requests to raw.githubusercontent.com that either are just repeated or there's something wrong with the SSL request, it's all encrypted so can't tell what's actually in the request but it doesn't look like anything is being returned.

Lots and lots of the following which occur after 2 complete request/responses to github.com which I presume is a redirect to the actual content at raw.githubusercontent.com
![screen shot 2017-02-09 at 09 44 28](https://cloud.githubusercontent.com/assets/525550/22777822/62b29aea-eeac-11e6-8970-dfd43721d252.png)

I tried to attach the pcap file but it's not allowed here.

**Comment by Jolty95** [comment] 2017-02-09 09:48
I know what to do now...
For some reason you don't have release-bootstrap and unofficial-bootstrap file (it's a plain text file not the `.nds` file.
Follow this steps please and send me back two logs.ini files:
Steps:
1. delete log and log.ini
1. install this version (don't bother in deleting anything, just install with FBI)
1. open TWLoader and if it doesn't close, shutdown your console and copy log.ini file and send me.
1. now we have one log file, so put this two files ([release-bootstrap](https://github.com/Jolty95/TWLoader-update/blob/master/release-bootstrap?raw=true) and [unofficial-boostrap](https://github.com/Jolty95/TWLoader-update/blob/master/unofficial-bootstrap?raw=true) in `SD:\_nds\twloader` 
1. delete log.ini from sd and open again TWLoader and after closing it, send me back that log.ini file too :)

**Comment by bui** [comment] 2017-02-09 09:59
Log 1
````
Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message:<release-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading release-bootstrap ver file.>
````

Log 2
````
Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message:<Re-opening release bootstrap ver file.>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file #2:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message: <Reading unofficial bootstrap ver file:> 	Additional info:<Unofficial 16459a2 >
````

TWLoader worked after placing the two bootstrap text files. I don't know if you were aware, but in the 3.3.1 release they are included, but inside `sdmc://_nds/`. Could it have been an oversight, or do they need to be in both directories?

![image](https://cloud.githubusercontent.com/assets/1788767/22778328/76169a3a-eeae-11e6-8fb8-ec18e3921d91.png)

**Comment by Jolty95** [comment] 2017-02-09 10:03
@bui your problem was that the method we use to download is not working right on you. I don't know how to fix it tho....but, just a question, was twloader update, boxarts, etc downloading fine? If you don't mind, I can send you another debug version to test if now it's downloading for you
And about 3.3.1 that was a great mistake in my side... sorry for that. .nds files should be in `SD:\_nds`  and ver files of bootstrap in `SD:\_nds\twloader`

**Comment by Jolty95** [comment] 2017-02-09 10:03
Oh, just delete log.* files in twloader folder again :)

**Comment by bui** [comment] 2017-02-09 10:07
Boxart download is fine, but when I tried to update bootstrap in settings, it freezed.

And sure, I don't mind testing to try and fix the issue.

**Comment by Jolty95** [comment] 2017-02-09 10:15
Sorry the delay :)
![qr](http://www.qrcode.es/wp-content/themes/ultra/qrcdr/qrcodes/3a6e37914fd707cb67c179d3f36ed4e9.png?1486635228723)
Just press X and later Y or vice versa to update bootstrap string. It should change. If 3ds crash/freeze let me know and send me back the log again :)

**Comment by elliot-forty-two** [comment] 2017-02-09 10:21
I tried to install using the QR code and it failed in FBI with "Failed to verify TLS certificate (60)". This seems like a similar problem to what I was seeing in the pcap.

**Comment by bui** [comment] 2017-02-09 10:22
````
Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message:<Re-opening release bootstrap ver file.>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file #2:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message: <Reading unofficial bootstrap ver file:> 	Additional info:<Unofficial 16459a2 >
````

Also, yes, I also got TLS verification errors when installing the CIA through github servers. Looks like that might be the problem?

**Comment by bui** [comment] 2017-02-09 10:26
@elliot-forty-two What region is your 3DS, and what system version are you on? I'm wondering what might cause different systems to have different CAs in the trust store.

**Comment by elliot-forty-two** [comment] 2017-02-09 10:28
I'm EUR region, 3DS actually from Australia originally. I'm running 11.2.0-35E with A9HL and Luma3DS.

**Comment by bui** [comment] 2017-02-09 10:34
What's more bizarre is that if I open `https://raw.githubusercontent.com/Jolty95/TWLoader-update/master/release-bootstrap` in the 3DS browser it loads fine. Not sure what's up with that.

**Comment by Jolty95** [comment] 2017-02-09 10:39
Sorry for the QR.
Can you download manually from [here](https://github.com/Jolty95/TWLoader-update/blob/master/beta/TWLoader.cia?raw=true) ?
I have no problem downloading from github. Are you using any custom wifi options?

**Comment by bui** [comment] 2017-02-09 10:42
Nope. Everything is default. GitHub HTTPS works fine in the internet browser, the issue seems to be with homebrew applications...

**Comment by Jolty95** [comment] 2017-02-09 10:43
Using the cia I posted bootstrap text have changed?

**Comment by bui** [comment] 2017-02-09 10:49
Changed where? It is still `16459a2` and `0.4.0` in options. Log file is the same even after deleting. I am using the bootstrap files you posted earlier. Every time I try to update unofficial/release, that version file is deleted before freezing.

**Comment by Jolty95** [comment] 2017-02-09 10:52
That's what I was asking :P
Now we confirm the problem is that your console (and @elliot-forty-two too) doesn't download from github bootstrap ver files...It shouldn't freeze at all tho

**Comment by elliot-forty-two** [comment] 2017-02-09 10:55
The freeze is because it's re-trying the download in a loop. downloadFile checks for 3xx and 200 codes but I don't think the request is even getting to anything HTTP related and failing the SSH handshake. Is there an error state you can check in that loop to break out if SSH fails? It wouldn't freeze then but we still have the problem of TLS erroring.

@Jolty95 can you download using FBI and the QR you posted or do you get the TLS error?

**Comment by bui** [comment] 2017-02-09 10:56
I think it might be a ctrulib issue since FBI is also failing to download from the same host. But the issue of TWLoader freezing when the download fails should still be fixed.

**Comment by Jolty95** [comment] 2017-02-09 10:59
I can download the QR and it install fine that's why I really don't understand why it's freezing at all. downloadFile method is not too good to be honest but before that was "working" fine (or at least no one notice about that problem you know) I don't know how to handle the freeze neither :(

**Comment by elliot-forty-two** [comment] 2017-02-09 11:04
Well there's a `if (ret==0)` that has no `else` and maybe `httpcBeginRequest(&context);` needs to have its result checked. I'd put in some debug myself but my compiles don't work for me.

**Comment by Jolty95** [comment] 2017-02-09 11:04
Just to be sure. You both have change a region change?

**Comment by Jolty95** [comment] 2017-02-09 11:04
@elliot-forty-two thanks for pointing that out ;) I'll take a look to that too

**Comment by bui** [comment] 2017-02-09 11:05
I haven't changed my 3DS' region, nope.

**Comment by elliot-forty-two** [comment] 2017-02-09 11:06
I haven't made any changes to my region using Luma, it's the original region. I'm physically in the UK now but the 3DS was bought in Australia which is also part of the EUR region.

**Comment by Jolty95** [comment] 2017-02-09 11:08
Ups, I misread, sorry.
I'll handle what @elliot-forty-two  said and post here a debug cia. Hopes this time won't freeze (and sorry for the problem but it's difficult to fix something that it's working ok in my side :()

**Comment by elliot-forty-two** [comment] 2017-02-09 11:13
That's OK. I know how difficult it is to fix these things if you can't actually reproduce the issue.

**Comment by Jolty95** [comment] 2017-02-09 11:30
Done :)
Now if your console is an OLD and you turn the wifi slider off, it doesn't freeze :D
Please, test it :)
![qr](http://www.qrcode.es/wp-content/themes/ultra/qrcdr/qrcodes/3a6e37914fd707cb67c179d3f36ed4e9.png?1486639766016)

**Comment by bui** [comment] 2017-02-09 11:35
Yep, the freeze problem is fixed now. Thanks!

**Comment by Jolty95** [comment] 2017-02-09 11:36
Yeah!! ^^
Can you go to settings, press X and Y later and post the log.ini to be completly sure the problem (at least the freeze one) is solve forever? :)

**Comment by bui** [comment] 2017-02-09 11:44
````Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message:<Re-opening release bootstrap ver file.>
Method: <download.checkBootstrapVersion()> :
		Message: <Reading release bootstrap ver file #2:> 	Additional info:<Release v0.4.0  >
Method: <download.checkBootstrapVersion()> :
		Message:<unofficial-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading unofficial-bootstrap ver file.>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message:<release-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading release-bootstrap ver file.>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <download.checkBootstrapVersion()> :
		Message:<unofficial-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading unofficial-bootstrap ver file.>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <download.checkBootstrapVersion()> :
		Message:<Checking bootstrap version>
Method: <download.checkBootstrapVersion()> :
		Message:<release-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading release-bootstrap ver file.>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <download.checkBootstrapVersion()> :
		Message:<unofficial-bootstrap ver file not found.>
Method: <download.checkBootstrapVersion()> :
		Message:<downloading unofficial-bootstrap ver file.>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
Method: <downloadFile.error> :
		Message:<An error has ocurred trying to get responce status code>
````

**Comment by bui** [comment] 2017-02-09 11:46
It does seem that attempting to update *does* delete the existing file... that probably shouldn't happen, in case the update fails.

**Comment by Jolty95** [comment] 2017-02-09 11:46
At least we now the two problems.
First is that @Jolty95 need to learn more English. Response is with S :P
Second, httpcGetResponseStatusCode was causing the issue.

**Comment by Jolty95** [comment] 2017-02-09 11:47
@bui You're right. But it that happen, No version available will show in settings (I have to modify a bit the code to show that)

**Comment by Jolty95** [comment] 2017-02-09 11:54
[This](https://github.com/Jolty95/TWLoader-update/blob/master/beta/TWLoader.cia?raw=true) is going to be the PR version ;)

**Closed** 2017-02-09 19:45 UTC
Labels: solved in nighty's
