### ISSUE TITLE
Freezes at "Downloading..." during update

### ISSUE THREAD

**Issue by weirdal3333** [Robz8/TWLoader#296] opened 2017-06-15 04:54 UTC
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [ x ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ x ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ x ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ x ]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [ x ]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

The version number should be 5.3.0 and it should download the latest twloader files.

### Actual behaviour

When you try to update, it freezes at the "Checking Wi-Fi status..." screen, even though it already checked for a new version.
My thought is that maybe it can't figure out if it's up to date or not. Even though it's supposed to be version 5.3.0, it shows up as 5.2.2.

### Steps to reproduce

1. Go to Twloader settings
2. Check for updates on page 2
3. Accept the update request

**Comment by Robz8** [comment] 2017-06-15 04:58
OK, I'm getting the issue as well.

**Comment by Robz8** [comment] 2017-06-15 05:10
I fixed the latest version to contain the correct version number, but the freezing issue persists.

**Comment by mariogamer2** [comment] 2017-06-15 18:09
Welp Im not getting the correct version number... It's always displays 5.1.0

**Comment by weirdal3333** [comment] 2017-06-16 13:26
What's the wifi check for? Wouldn't it be better to have a timeout for the download to start?
Like maybe tell the user to "Check your internet connection" when the download fails.

**Comment by Robz8** [comment] 2017-06-16 19:09
Actually it's not checking for WiFi, when it freezes. It's gets a previous framebuffer for some reason.

**Comment by weirdal3333** [comment] 2017-06-17 22:46
I don't know if this helps, but I can't exit twloader with any method other than a forced shutdown. 

However, I CAN still use Rosalina along with debugging. I don't know how to use debugging features, though.

**Comment by Robz8** [comment] 2017-06-20 02:49
Next version will no longer show the message, and instead show the correct message, but sadly will still freeze.

**Comment by TheMCNerd2017** [comment] 2017-06-25 18:54
Is there any actual reason for the app crashing when people attempt to update through the app? This has been a issue for quite some time now.

**Comment by Robz8** [comment] 2017-06-25 21:20
We'll have to wait for @Jolty95 to look into this issue.

**Comment by TheMCNerd2017** [comment] 2017-06-26 00:05
Oh, OK.

**Comment by Jolty95** [comment] 2017-06-26 15:12
@Robz8 Ok.

**Comment by Jolty95** [comment] 2017-06-26 15:33
I need more info to solve this problem. 
Can someone post new steps to reproduce the problem?

**Comment by Robz8** [comment] 2017-06-26 15:37
Change the TWLoader version to a lower one.

**Comment by Jolty95** [comment] 2017-06-26 15:37
So, problem is downloading a new version, not checking, right?

**Comment by Robz8** [comment] 2017-06-26 15:41
Yes.

**Comment by Jolty95** [comment] 2017-06-26 15:55
"Now downloading latest TWLoader version..."
"(GUI, CIA)"
"Do not turn off the power."

This?

**Comment by maorninja** [comment] 2017-06-26 15:58
Yeah, that.

What I did to overcome the issue is just do a manual update.

**Comment by Jolty95** [comment] 2017-06-26 15:59
I think I found the problem.

**Comment by Jolty95** [comment] 2017-06-26 19:02
This issue will take me a while (some days), but I'll fix it in these days.

**Comment by Robz8** [comment] 2017-06-26 19:06
Ok.

**Comment by weirdal3333** [comment] 2017-06-27 19:06
Thanks! I am doing manual updates until it gets fixed.
Thanks for having a confirmation screen for the auto update.
(You're already using better practices than windows)

**Comment by Jolty95** [comment] 2017-06-28 14:39
Fixed in PR :)

**Closed by Jolty95** 2017-06-28 14:39 UTC
Labels: bug, solved in nighty's

**Comment by TheMCNerd2017** [comment] 2017-06-28 21:12
Yes! Thank you for fixing this little annoying bug.

**Comment by curtisgroth** [comment] 2017-12-21 23:04
Just gonna jump in here, still here on 5.5.1. I know this is me reviving an old thread, but I'm not sure if it was patched in the old update, meaning it could potentially still be there? (Not sure, but I know that 5.5.1 doesn't work for me.) Will try manual update to see if that works. Tried shutting down from Rosalina menu, it let me choose it but isn't shut off yet.
