### ISSUE TITLE
New Super Mario Bros "saved data could not be read."

### ISSUE THREAD

**Issue by MTMasterGaming** [Robz8/TWLoader#480] opened 2018-05-01 04:57 UTC
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [ ]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [ ]  < 11.4
- [x]  >= 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

It should load the game instead of saying that saved data could not be read.
### Actual behaviour

I get a message saying "Saved data could not be read. Turn the power off & reinstert the Game Card."

### Steps to reproduce

1. Get New Super Mario Bros rom, place it in the folder
2. Set it as donor rom
3. Launch the game, and you will get the message

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
```

**Comment by Barawer** [comment] 2018-05-01 07:05
Try setting mario kart as the donor, not super mario bros.

**Comment by Robz8** [comment] 2018-05-01 13:34
^ this

**Comment by yrgentmessage** [comment] 2018-05-01 19:00
? how did u get loader to wokr because mine is the 2ds xl modle and wont let me rolina menu to miss when i hold l down then select buttion combo i evan put the right folder on to sd card so how were you able to pull it off with fbi showing up on yours when it doesent do to mine ? i have big problem i think i evan tryed hour glass and nothing appeared so yeah

**Comment by MTMasterGaming** [comment] 2018-05-02 04:04
Thanks! Didn't completely understand that I was supposed to set it to mario kart, not new super mario bros. I thought I just needed the mario kart rom. 
@yrgentmessage this is for NWTLoader. You're talking about issues with Rosalina and FBI, which doesn't really have anything to do with this issue I posted, or NWTLoader. I suggest you ask for support in the homebrew discord (https://discord.gg/C29hYvh) they will be able to help you much better than here.

**Comment by Robz8** [comment] 2018-05-02 04:42
Closing, since the issue is solved.

**Closed by Robz8** 2018-05-02 04:42 UTC
