### ISSUE TITLE
Claims to be Checking Version, yet hangs indefinitely

### ISSUE THREAD

**Issue by RubberBrony** [Robz8/TWLoader#58] opened 2017-01-14 23:22 UTC
Whether set to check for updates on launch, or through the Settings menu, TWLoader stops entirely.
I've waited at least 30 minutes for both selections, and tried other WiFi networks.
I am on the current version (2.3.1 as of writing this).

If you need more information, I'll gladly provide!

**Comment by Robz8** [comment] 2017-01-14 23:25
That'll be fixed in the next release.

**Comment by Multipixelone** [comment] 2017-01-15 02:21
How do I fix this for now? Can I edit a file??

**Comment by FirkePizdek69** [comment] 2017-01-15 12:20
Your latest release says it is confirmed that the issue is fixed, but my 3ds still hangs on that screen, the only way i can get into twloader is by turning of wireless connection on my 3ds and turning off latest twloader check in twloader settings

**Comment by deadair3210** [comment] 2017-01-16 03:58
Agreed, check still freezes the entire system, have to hard reboot

**Comment by Jolty95** [comment] 2017-02-01 18:28
Solved some release before.

**Closed by Jolty95** 2017-02-01 18:28 UTC
