### ISSUE TITLE
Data Abort when updating nds-bootstrap, and on all subsequent launches of TWLoader

### ISSUE THREAD

**Issue by RubberBrony** [Robz8/TWLoader#285] opened 2017-06-08 06:27 UTC
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS 8.0
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

TWLoader downloads updated version of nds-bootstrap, and opens on subsequent launches

### Actual behaviour

TWLoader data aborts while updating nds-bootstrap, and data aborts on all subsequent launches

### Steps to reproduce

1. Start TWLoader
2. Go to Settings
3. Press X or Y to update nds-bootstrap. It should crash.
4. Press any button to reboot
5. Start TWLoader. It should crash.

### Stack trace and console log

If you are getting a crash or want to upload your log file, please, write that information between the following quotation marks.

```
crash_dump1 is  after attempting to update nds-bootstrap, crash_dump2 and crash_dump3 are after rebooting and attempting to launch.
```

[crash_dump1.txt](https://github.com/Robz8/TWLoader/files/1060081/crash_dump1.txt)
[crash_dump2.txt](https://github.com/Robz8/TWLoader/files/1060082/crash_dump2.txt)
[crash_dump3.txt](https://github.com/Robz8/TWLoader/files/1060080/crash_dump3.txt)

**Comment by RubberBrony** [comment] 2017-06-08 06:30
It should be noted that on Luma3DS 8.0, the crash handler can't be disabled, and so things that *wouldn't* crash previous versions of Luma3DS will crash 8.0

**Comment by Boured** [comment] 2017-06-08 08:08
I can confirm this, I had to reinstall the entire thing (folders and all) In order to make it functional again. I do hope it gets fixed in the future.

**Comment by Jolty95** [comment] 2017-06-08 08:14
It's the same as this issue?
https://github.com/Robz8/TWLoader/issues/282

**Comment by Boured** [comment] 2017-06-08 08:20
Pretty much, i'm new to TWLoader, so where would I find the Nightlies?

**Comment by Jolty95** [comment] 2017-06-08 08:27
ATM you can only get nighties if you compile TWLoader by yourself. But release will be ready really soon :)
And, since this issue is duplicated, I'm closing this now ;)

**Closed by Jolty95** 2017-06-08 08:27 UTC
