### ISSUE TITLE
App continually updates itself

### ISSUE THREAD

**Issue by deadair3210** [Robz8/TWLoader#167] opened 2017-02-07 00:59 UTC
1. Open app

2, Auto Update triggers, and installs the latest versions

3. updates nds-bootstrap

4.App Closes to home menu

5, GOTO 1

**Comment by Roboron3042** [comment] 2017-02-07 02:55
Same here...

**Comment by Robz8** [comment] 2017-02-07 03:18
For now, in "sdmc:/_nds/twloader/settings.ini", set AUTODOWNLOAD in [FRONTEND] to 0.

**Comment by deadair3210** [comment] 2017-02-07 03:33
Didn't work, had to delete settings file and let the app recreate it

**Comment by tetsuo55** [comment] 2017-02-07 08:37
Yeah the old setting file(s) needs to be deleted

**Comment by kade-robertson** [comment] 2017-02-07 13:36
@Robz8 

I'm not sure if this is by design or not, but you check the version of bootstrap with `checkBootstrapVersion()` and do nothing with the data. Shouldn't this function be returning some value to indicate that the version is new? I'm not very familiar with your codebase and with 3DS development in general so I will leave this to someone else to figure out (especially as I can't do debugging right now), but I would imagine the change would be something like:

(Before)

    downloadBootstrapVersion(true);
    checkBootstrapVersion();
    downloadFile(DOWNLOAD_OFFICIALBOOTSTRAP_URL,"/_nds/release-bootstrap.nds", MEDIA_SD_FILE);

(After)

    downloadBootstrapVersion(true);
    if (checkBootstrapVersion()) {
        downloadFile(DOWNLOAD_OFFICIALBOOTSTRAP_URL,"/_nds/release-bootstrap.nds", MEDIA_SD_FILE);
    }

However, this will never work if you don't check the version of the current nds-bootstrap, as of now this isn't stored or checked anywhere as far as I can tell. So, if the intended behaviour is to download the bootstrap on launch every single time, you can probably close this issue.

**Comment by Jolty95** [comment] 2017-02-07 14:16
@kade-robertson  I was the one that create checkBootstrapVersion() and that method only check, download and store the string that is shown in settings. I wrote it like this because I don't want to make it to use always latest version of bootstrap. Also downloadbootstrapversion is for downloading the "ver" string for bootstrap, not the .nds :)

**Comment by kade-robertson** [comment] 2017-02-07 14:31
@Jolty95 I'm not sure I understand, downloadFile clearly downloads the bootstrap file every time.. There is no condition preventing this:

    downloadFile(DOWNLOAD_OFFICIALBOOTSTRAP_URL,"/_nds/release-bootstrap.nds", MEDIA_SD_FILE);

from running every single boot. I know this is the behaviour because I use this app nearly every day and it downloads the bootstrap .nds every time. So this currently does always use the latest version of bootstrap.

**Comment by Jolty95** [comment] 2017-02-07 14:34
@kade-robertson  If you have bootstrap set to auto download at launch, it will download no matter what version do you have in SD

**Comment by kade-robertson** [comment] 2017-02-07 14:40
@Jolty95 As far as I can tell that's what the original issue was for. Is there a particular reason this doesn't check if the version is different first? I know the projects are separate but surely this app could check so the file doesn't have to be downloaded every time.

**Comment by bakawun** [comment] 2017-02-07 14:43
I have been looking at the code too after reading what @kade-robertson had to say and i think he may be on to something.

To me it looks like we are always deleting the ver files for nds_bootstrap before trying to read the version.
This is very different from the cia updating code where we redownload the ver file before reading it to update the view in settings.

Also this and https://github.com/Robz8/TWLoader/issues/169 are duplicate tickets, they both report the hang on checkBootstrapVersion()

**Comment by Jolty95** [comment] 2017-02-07 14:45
@kade-robertson If you set bootstrap to auto download it will download on every launch of TWLoader. In the other side, is TWLoader GUI checker the problem (that other version was working right) that it's causing the issue. There is NOTHING wrong with bootstrap method afaik.
Also, why I didn't wanted bootstrap to check before downloading? Simply. I wanted to do it different from GUI checkUpdate method and I wanted to redownload even if bootstrap installed vs bootstrap internet were the same version to override bootstrap.nds from SD (for example after user using his/her own bootstrap etc)

**Comment by bakawun** [comment] 2017-02-07 15:01
@Jolty95 I don't think the download of nds is failing but the setting of the boostrap version for settings screen

**Comment by Jolty95** [comment] 2017-02-07 15:03
@bakawun i'm completly sure checkUpdate is returning always zero (that's mean that there's an update pending) but magically when you put a "log" file to enable logs, checkUpdate works fine ._.

**Comment by bakawun** [comment] 2017-02-07 15:11
@Jolty95 you do not check the wifi status inside the checkupdate function before trying to download the ver file, could that be it?

**Comment by Jolty95** [comment] 2017-02-07 15:16
@bakawun Imaging that that's the problem. checkUpdate start working and remove "ver" file, create the int res variable and call downloadFile. that method also checkWifiStatus so I don't think that's the problem because res = -1 and checkUpdate() = 0 when autodownload is on (and no log file)

**Comment by bakawun** [comment] 2017-02-07 15:18
I think you need to add !isUnknown  to here https://github.com/Robz8/TWLoader/blob/master/gui/source/download.cpp#L230

**Comment by Jolty95** [comment] 2017-02-07 15:19
(didn't see the edited)
I don't really know what's  isUnkown variable and before that was working all fine

**Comment by bakawun** [comment] 2017-02-07 16:28
@Jolty95 could it be this: https://github.com/Robz8/TWLoader/blob/master/gui/source/download.cpp#L500

That is the only place where you give res a value of 0.
Does it perhaps need to be -1?

**Comment by Jolty95** [comment] 2017-02-07 16:29
@bakawun  i can't test atm, maybe @Robz8 can get us some light to this problem.

**Comment by bakawun** [comment] 2017-02-07 17:59
@Jolty95 i found the issue but I am not sure how to fix it.
The problem seems to be that downloading the version files for bootstrap can go into an infinite loop

**Comment by Jolty95** [comment] 2017-02-07 18:37
@bakawun I don't mind if anyone want to modify those codes :P Only log and keyboard files/methods have a "please do not modify" section but others that I didn't wrote that I really don't mind :P 
Also as I said yesterday in the temp we're humans and sometimes bugs appear and we didn't notice them till it's a bit late ;)

**Comment by Jolty95** [comment] 2017-02-08 11:22
Ok, I found the problem and I'm working on the update fix. Will be solve soon

**Comment by Jolty95** [comment] 2017-02-08 12:09
https://github.com/Robz8/TWLoader/pull/174

**Comment by Robz8** [comment] 2017-03-20 17:34
Re-opening, since the issue returned in v4.2.0.

**Comment by Jolty95** [comment] 2017-03-20 17:38
@Robz8 but this issue is related again with #174 ?

**Comment by Robz8** [comment] 2017-05-03 05:41
The issue is one again fixed in v4.3.1.

**Closed by Robz8** 2017-05-03 05:41 UTC
