### ISSUE TITLE
DS Bootscreen's text is out of screen when using other languages (system language)

### ISSUE THREAD

**Issue by OdnetninI** [Robz8/TWLoader#317] opened 2017-07-06 22:24 UTC
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [X]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [ ]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [X]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

Spanish bottom boot screen must be centered.

### Actual behaviour

Spanish bottom boot screen is out of screen.

### Steps to reproduce

1. Start a game with spanish language

![photo_2017-07-07_00-23-37](https://user-images.githubusercontent.com/1885102/27935309-8cc2a560-62aa-11e7-96b3-c343f96fd53d.jpg)
![photo_2017-07-07_00-23-32](https://user-images.githubusercontent.com/1885102/27935310-8f7508c0-62aa-11e7-98a4-6d79579d90a0.jpg)

**Comment by Jolty95** [comment] 2017-07-06 23:04
Sorry but I'm unable to reproduce this. 
I have my console set to spanish and it's showing right. 
@OdnetninI Have you pressed any button? Can you show your settings .ini file too?

**Comment by Jolty95** [comment] 2017-07-06 23:14
![bot_0000](https://user-images.githubusercontent.com/21294047/27936569-930ed98c-62b1-11e7-892e-aecc7a184890.png)

This is what I get

**Comment by OdnetninI** [comment] 2017-07-07 13:34
Sry for the late response, here is my settings.ini

[settings.ini.txt](https://github.com/Robz8/TWLoader/files/1131104/settings.ini.txt)

**Comment by OdnetninI** [comment] 2017-07-07 13:40
Okey, i Found why.
I selected spanish at language selection, with that, there's no problem, but if i put it on system language and that language is spanish, the bug appears.

**Comment by Robz8** [comment] 2017-07-07 13:40
Yeah, I figured.

**Comment by Jolty95** [comment] 2017-07-07 13:45
@Robz8 Are you working on a fix for this issue? :)

**Comment by OdnetninI** [comment] 2017-07-07 13:51
If needed, i can test on my console.

**Comment by Jolty95** [comment] 2017-07-07 13:54
@OdnetninI don't worry, I have reproduced the problem ;)

**Comment by Jolty95** [comment] 2017-07-07 13:57
BTW, "problem" is that language is -1, so [here](https://github.com/Robz8/TWLoader/blob/master/gui/source/dsbootsplash.cpp#L443) it render with english sizes [instead of spanish or other language size](https://github.com/Robz8/TWLoader/blob/master/gui/source/dsbootsplash.cpp#L523)

**Comment by Robz8** [comment] 2017-07-07 14:15
@Jolty95 If I have the time, yes.

**Closed** 2017-07-08 21:25 UTC
Labels: bug
